// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// initlist
List initlist();
RcppExport SEXP L3bin_initlist() {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        List __result = initlist();
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// bin2lonlat
List bin2lonlat(IntegerVector bins);
RcppExport SEXP L3bin_bin2lonlat(SEXP binsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< IntegerVector >::type bins(binsSEXP );
        List __result = bin2lonlat(bins);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// binlist
List binlist(CharacterVector filename, CharacterVector vname);
RcppExport SEXP L3bin_binlist(SEXP filenameSEXP, SEXP vnameSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector >::type filename(filenameSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type vname(vnameSEXP );
        List __result = binlist(filename, vname);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// vdatainfo
List vdatainfo(CharacterVector file);
RcppExport SEXP L3bin_vdatainfo(SEXP fileSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector >::type file(fileSEXP );
        List __result = vdatainfo(file);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
