# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Say my name. 
#'
#' Short message from sponsor. 
#' @export
rcpp_hello_world <- function() {
    .Call('L3bin_rcpp_hello_world', PACKAGE = 'L3bin')
}

#' Basic L3 bin files 
#'
#' Read from L3 bin. 
#' @param filename path to L3 bin OC file (HDF4)
#' @export
binlist <- function(filename) {
    .Call('L3bin_binlist', PACKAGE = 'L3bin', filename)
}

