# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Parameters from initbin. 
#'
#' Initbin. 
#' @export
initlist <- function() {
    .Call('L3bin_initlist', PACKAGE = 'L3bin')
}

#' Longitude and latitude from bin number.  
#'
#' Generate longitude and latitude coordinates from bin number. 
#' @export
bin2lonlat <- function(bins) {
    .Call('L3bin_bin2lonlat', PACKAGE = 'L3bin', bins)
}

#' Basic L3 bin files 
#'
#' Read from L3 bin. 
#' @param filename path to L3 bin OC file (HDF4)
#' @export
binlist <- function(filename, vname) {
    .Call('L3bin_binlist', PACKAGE = 'L3bin', filename, vname)
}

#' Vdata names and field names in HDF4. 
#' 
#' Retrieve vdata names and their field names from HDF4. 
#' @param file name of HDF4 file containing Vdata
#' @return Named list, each element with the field names of the named Vdata. 
#' @export
#' @examples
#' \dontrun{
#' f <- "A2014202.L3b_DAY_PIC.main"
#' if (!file.exists(f)) {
#'   download.file(sprintf("http://oceandata.sci.gsfc.nasa.gov/cgi/getfile/%s.bz2", f), sprintf("%s.bz2", f), mode = "wb")
#'   system(sprintf("bunzip2 %s.bz2", f))
#' } 
#'   vdatainfo(f)
#' 
#' 
#' }
vdatainfo <- function(file) {
    .Call('L3bin_vdatainfo', PACKAGE = 'L3bin', file)
}

